# Generated by Django 4.1.5 on 2023-01-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('publisher', models.CharField(max_length=120)),
                ('publishedYear', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
